spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

crawler:
  server:
    url: ${CRAWLER_SERVER_URL}

cors:
  mapping-url: ${CORS_MAPPING_URL}

server:
  url: ${SERVER_URL}