spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

cors:
  mapping-url: ${CORS_MAPPING_URL}

server:
  url: ${SERVER_URL}